#!/usr/bin/env bash

set -e

usage() {
  err "Usage: $0 <num> [name glob] [other args]"
}

if [ $# -lt 1 ]; then
  usage
fi

num="$1"
shift
if [[ ! "$num" =~ [0-9]* ]]; then
  usage
fi

if [ $# -eq 0 ]; then
    num="$(($num - 1))"
    find * -maxdepth "$num" -type d
else
    find "$@" -maxdepth "$num" -type d
fi
